function F(b,f,d){function l(){0!=I&&(J=(new Date).getTime()-I)}function k(a){G=G|a;z.narme=G}function u(a){q.a("l2("+a+")");E=E|a;T()?(l(),I=0):0==I&&(I=(new Date).getTime());z.narm=E;q.a("l2e")}function r(a){K=K|a;z.naral=K}var q=new O,g=d&&d.dvObj||window.$dv,m=d&&d.impressionId||window.$uid,w=window.lg||f,h=Array(w.wb),c=w.lb/w.mc+1,a=null,e="",p={},n=0,x=Array(w.wb),t={$:{M:null,N:null,C:null,B:null,kf:!1},f:{A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,kf:!1},Aa:{Ob:null,Nb:null},
Tb:0},v={},A={},B,C,y={},M={},P=6,Q=!1;this.Yf=function(a){P=a};for(f=0;f<w.wb;f++)x[f]="b"+f;var D={};d&&g&&g.CommonData&&(D.ctx=d.yb,D.cmp=d.xb,D.btreg=d.btreg,D.btadsrv=d.ab,D.uid=d.Cb,D.brid=g.CommonData.BrowserId,D.brver=g.CommonData.BrowserVersion,D.tstype=g.CommonData.Scenario);D.jsver=b?b:null;var z={},H={},I=0,J="",L="",K=0,E=0,G=0,N=0;this.hd=function(){return I};this.Nd=function(a){N=N|a;z.vct=N};this.Md=function(e){a=e;H.strp=a;this.Md=function(){}};this.rc=function(){return(new Date).getTime()};
var U=this.rc();this.af=function(){return U};this.Mf=function(){E=E&-3;G=G&-2;G&=-3};this.Qb=function(){u(2)};this.Xf=function(){k(8);this.Hc()};this.Hc=function(){u(4)};this.Id=function(){r(8);this.Qb()};this.Sd=function(a){r(16);z.dbg9=a};this.Td=function(){r(1)};this.Vf=function(){this.Qb();k(1)};this.Uf=function(){this.Qb();k(2)};this.ob=function(a,e){u(8);L=q.Te(a,e)};this.Rf=function(){q.a("l1");E=E&-3;u(1);q.a("l1e")};this.Ld=function(){u(16)};this.Me=function(){return h};this.Jd=function(a,
e){m=m||d&&d.impressionId||window.$uid;q.a("ie15");if(0<=a.g){var p=Math.floor(a.g/w.mc);0<a.g%w.mc?p++:0<a.g&&p++;isNaN(h[p])&&(h[p]=0);h[p]+=e;a.H&&p>=c||0==a.H&&6<=p?n+=e:timeStampTotalBuckets=n=0}q.a("ie15e")};this.Tf=function(a){var e=a.qd;null!=a.qd&&(v.advisonl=e);null!=a.pd&&(v.adabvvponl=a.pd);z.dbg8="CSS1Compat"===document.compatMode?1:0;q.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(z.dbg10=document.documentMode);q.a("ff52e")};this.nb=function(a){q.a("ie14");null!=
a&&(M.adbtftopg=a)};this.Sf=function(a){null!=a&&(t=a)};this.Kd=function(a){q.a("ie19");this.Sf(a.u);this.$f();q.a("ie19e")};this.Wd=function(){null!=t.$.M&&(y.vptoscrx=Math.round(t.$.M));null!=t.$.N&&(y.vptoscry=Math.round(t.$.N));null!=t.$.C&&(y.vpwdth=Math.round(t.$.C));null!=t.$.B&&(y.vphgt=Math.round(t.$.B));null!=t.f.A&&(y.adtovpx=Math.round(t.f.A));null!=t.f.v&&(y.adtovpy=Math.round(t.f.v));null!=t.f.K&&(y.adtopgx=Math.round(t.f.K));null!=t.f.L&&(y.adtopgy=Math.round(t.f.L));null!=t.f.D&&(y.adtoscrx=
Math.round(t.f.D));null!=t.f.F&&(y.adtoscry=Math.round(t.f.F));null!=t.Aa.Ob&&(y.scrwdth=Math.round(t.Aa.Ob));null!=t.Aa.Nb&&(y.scrhgt=Math.round(t.Aa.Nb));y.almesind=t.Tb};this.Xd=function(){if(B&&C){var a=t.f.o,e=t.f.j;B*C<a*e&&(A.dvp_adwdth=Math.round(B),A.dvp_adhgt=Math.round(C),!Q&&(1>=B||1>=C)&&1<a&&1<e&&($dv.registerEventCall(m,{adwdth:Math.round(a),adhgt:Math.round(e)}),Q=!0),B=a,C=e)}else B=null!=t.f.o?t.f.o:null,C=null!=t.f.j?t.f.j:null;null!=B&&(A.adwdth=Math.round(B));null!=C&&(A.adhgt=
Math.round(C))};this.$f=function(){l();for(var a=0;a<h.length;a++)h[a]&&(p[x[a]]=h[a]);this.Wd();this.Xd();q.G(y,v);q.G(y,A);q.G(y,M)};this.fd=function(){return 1E3<=n};this.Xe=function(a){var c={};m=m||d&&d.impressionId||window.$uid;var n=-1,h=q.Ue();try{g&&g.tags[m]&&g.tags[m].getTimeDiff&&(n=g.tags[m].getTimeDiff())}catch(b){}var x=[];q.G(c,D);switch(a){case 1:e=n;q.G(c,H);q.G(c,z);c.napt=J;q.G(c,y);c.dvp_log=h;c.napr=L;c.ismms=e;c.isumms=n;break;case 2:q.G(c,H);q.G(c,z);c.napt=J;q.G(c,y);c.dvp_log=
h;c.napr=L;c.isnmms=n;break;case 3:c.istoms=n;case 4:case 8:q.G(c,H);q.G(c,M);q.G(c,A);c.isbxdms=n;q.G(c,p);c.nvr=P;break;case 5:q.G(c,H);q.G(c,M);q.G(c,A);q.G(c,v);c.ismms=e||n;c.isiabvms=n;c.isuiabvms=n;break;case 16:q.G(c,H);q.G(c,z);c.napt=J;c.dvp_log=h;c.napr=L;c.ishems=n;break;case 7:return x.join("");default:q.G(c,H),q.G(c,p),q.G(c,z),q.G(c,v),c.napt=J,c.dvp_log=h,c.napr=L}c.evid=a;c.ctime=this.rc();return c};this.Le=function(){q.a("ie17");for(var a=[],c=0;c<w.wb;c++)a[c]=h[c]?h[c]:0;return a};
var T=this.Zc=function(){return 2==(E&2)&&8!=(K&8)||4==(E&4)||8==(G&8)&&8==(K&8)?!1:!0};this.Ff=function(a){q.a("l3");a=q.ia(a);q.a("cm3e");a&&(z.dbg5=a.w,z.dbg6=a.h);q.a("l3e")};return this}function R(b,f){var d=new O,l=b&&b.impressionId||window.$uid,k=0;this.ga=function(b,r){if(f){var q=f.Xe(b);r&&d.G(q,r);4==b||8==b?(5>k&&this.Fc(l,q,!0),k++):this.Fc(l,q,!1)}};this.Fc=function(b,f,d){$dv&&$dv.registerEventCall&&b&&$dv.registerEventCall(b,f,null,!d,d)}}
function S(){this.ga=function(){};this.Fc=function(){}}
function V(b,f,d,l){function k(){if(1==t){try{for(var a in n)x.removeChild(n[a]);e.document.body.removeChild(x)}catch(c){}t=!1}}function u(a){a=a||0;var c=g(0);c.td()?7<c.Bb()?(k(),A=v=t=!1):(t=!0,v=!1):20>a?(a++,setTimeout(u,50,a)):(t=v=A=!1,k())}function r(a){$dv&&$dv.tags&&$dv.tags[l]&&$dv.tags[l].getTimeDiff&&$dv.tags[l].getTimeDiff();if(null!==a.ub)for(var c=0;c<a.ub.length;c++){var e=g(c).Bb();0==c?e>B&&(B=e):e>C&&(C=e)}}function q(a){for(var c=!0,e=0;13>=e;e++)var p=g(e),c=c&(null!==p&&p.td());
if(!c)return null;a.Y={pb:!1,qb:!1,Za:!1,$a:!1};a.Wc=0;a.Fa=0;a.Jb=0;a.jb=0;a.sa=0;a.ub=Array(13);c=g(0).Bb();for(e=1;13>=e;e++)if(p=5<Math.abs(g(e).Bb()-c),a.ub[e]=p)switch(a.Wc++,e){case 2:a.Y.pb=!0;a.Fa++;break;case 3:a.Y.qb=!0;a.Fa++;break;case 4:a.Y.Za=!0;a.Fa++;break;case 5:a.Y.$a=!0;a.Fa++;break;case 6:case 7:case 8:case 9:a.Jb++;break;case 10:case 11:case 12:case 13:a.jb++}if(13===a.Wc)return a.sa=100,r(a),!0;c=a.ub;if(!1===c[1]){if(3<=a.jb||3<=a.Jb||3<=a.Fa)return r(a),null;if(2==a.jb&&2==
a.Fa)return a.sa=30,r(a),!1;a.sa=0;r(a);return!1}if(!0===c[1]&&(!0===c[2]&&!0===c[3]||!0===c[2]&&!0===c[4]||!0===c[3]&&!0===c[5]||!0===c[4]&&!0===c[5])||!0===c[1]&&4==a.Jb||!0===c[1]&&4==a.jb&&1<=a.Fa)return a.sa=50,r(a),!0;if(4==a.jb&&1<=a.Jb)return a.sa=30,r(a),!1;if(c[2]&&c[5]&&!(c[6]&&c[10]&&c[1]&&c[13]&&c[9])||c[4]&&c[3]&&!(c[8]&&c[12]&&c[1]&&c[11]&&c[7]))return r(a),null;a.sa=0;r(a);return!1}function g(a){a=n[a];var c=null;a&&(c=a.contentWindow);return c}function m(){for(var a=p.getBoundingClientRect(),
e=a.width,b=a.height,x=e/(1+h),w=b/(1+h),g=e/h,f=b/h,d=0;13>=d;d++){var v=a.left,t=a.top;switch(d){case 0:t=v=-1E5;break;case 1:v+=(e-c)/2;t+=(b-c)/2;break;case 3:v+=e-c;break;case 4:t+=b-c;break;case 5:v+=e-c;t+=b-c;break;case 6:v+=(e-g)/2;t+=(b-f)/2;break;case 7:v+=(e-g)/2+g;t+=(b-f)/2;break;case 8:v+=(e-g)/2;t+=(b-f)/2+f;break;case 9:v+=(e-g)/2+g;t+=(b-f)/2+f;break;case 10:v+=(e-x)/2;t+=(b-w)/2;break;case 11:v+=(e-x)/2+x;t+=(b-w)/2;break;case 12:v+=(e-x)/2;t+=(b-w)/2+w;break;case 13:v+=(e-x)/2+
x,t+=(b-w)/2+w}6<=d&&(v-=c/2,t-=c/2);var k=n[d];k.style.left=v+"px";k.style.top=t+"px"}}function w(){if(null!=p&&null!=p.parentNode){v=!0;x=e.document.createElement("div");e.document.body.appendChild(x);for(var a=0;13>=a;a++){var b=e.document.createElement("iframe");b.width=c;b.height=c;b.style.position="absolute";b.frameBorder="0";b.style.visibility="hidden";b.style.zIndex=-9999999;b.style.display="block";b.src="javascript:no=false;yes=true;("+function(){window.xf={te:100};window.dd=no;window.tb=
0;window.od=0;window.wd=0;window.og=no;window.Bb=function(){return window.wd};window.td=function(){return window.dd};window.rf=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;window.gc=function(){window.tb++;window.rf(window.gc,document)};window.gc();setInterval(function(){10>window.tb&&window.gc();window.wd=window.tb-window.od;window.od=window.tb},window.xf.te);window.setTimeout(function(){window.dd=yes},250)}.toString()+
")();";x.appendChild(b);n.push(b)}m()}}var h=Math.sqrt(2),c=1,a=new O,e=null,p=null,n=[],x,t=!1,v=!1,A=a.Hb(b,f,d);0==a.Da()&&(c=8);var B=0,C=0;this.ff=function(){0==v&&(0==(this.Ea()&&(null!=p&&a.sd(p,e)?!0:!1))?t=!1:(w(),u()))};this.Ea=function(){return A};this.Dc=function(){return t};this.Ta=function(a,c){e=a;p=c;this.ff()};this.ib=function(){if(0==t)return null;var a={};return null==q(a)?null:a}}
function W(b,f,d){function l(){var b=q.getClientRects()[0];if(!m||!b||m.left!==b.left||m.right!==b.right||m.top!==b.top||m.bottom!==b.bottom){m=b;for(var h=b.right-b.left,c=b.bottom-b.top,a=h/(1+u),e=c/(1+u),p=h/u,n=c/u,x=0;13>=x;x++){var g=Math.round(5*Math.random()),f=b.left+r.document.body.scrollLeft,d=b.top+r.document.body.scrollTop;switch(x){case 0:d=f=-1E5;break;case 1:f+=(h-1)/2+g;d+=(c-1)/2+g;break;case 2:f+=g;d+=g;break;case 3:d+=g;f+=h-1-g;break;case 4:f+=g;d+=c-1-g;break;case 5:f+=h-1-
g;d+=c-1-g;break;case 6:f+=(h-p)/2+g;d+=(c-n)/2+g;break;case 7:f+=(h-p)/2+p-g;d+=(c-n)/2+g;break;case 8:f+=(h-p)/2+g;d+=(c-n)/2+n-g;break;case 9:f+=(h-p)/2+p-g;d+=(c-n)/2+n-g;break;case 10:f+=(h-a)/2+g;d+=(c-e)/2+g;break;case 11:f+=(h-a)/2+a-g;d+=(c-e)/2+g;break;case 12:f+=(h-a)/2+g;d+=(c-e)/2+e-g;break;case 13:f+=(h-a)/2+a-g,d+=(c-e)/2+e-g}6<=x&&(f-=.5,d-=.5);f=Math.round(f);d=Math.round(d);g=r.document.getElementById("OVVBeaconContainer_"+x);g.style.left=f+"px";g.style.top=d+"px"}}}function k(){if("https://cdn.zentrick.com/openvv/2.5.4/OVVBeacon.swf"!=
"LRU_FWS_NOCAEB".split("").reverse().join("")){for(var b=0;13>=b;b++){var h=r.document.createElement("DIV");h.id="OVVBeaconContainer_"+b;h.style.position="absolute";h.style.zIndex=-99999;h.innerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="1" height="1"><param name="movie" value="https://cdn.zentrick.com/openvv/2.5.4/OVVBeacon.swf" /><param name="quality" value="low" /><param name="flashvars" value="id='+b+"&index="+b+'" /><param name="bgcolor" value="#ffffff" /><param name="wmode" value="transparent" /><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" />\x3c!--[if !IE]>--\x3e<object id="OVVBeacon_'+
b+'" type="application/x-shockwave-flash" data="https://cdn.zentrick.com/openvv/2.5.4/OVVBeacon.swf" width="1" height="1"><param name="quality" value="low" /><param name="flashvars" value="id='+b+"&index="+b+'" /><param name="bgcolor" value="#ff0000" /><param name="wmode" value="transparent" /><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" />\x3c!--<![endif]--\x3e</object>';r.document.body.insertBefore(h,r.document.body.firstChild)}l.bind(this)();setInterval(l.bind(this),
500)}}var u=Math.sqrt(2),r,q,g=new O,m;this.Ac=function(){return g.Bc(b,f,d)};this.Ta=function(b,h){r=b;q=h;k()};this.ib=function(){var b;a:{for(var h=b=0,c=0,a=0,e=Array(13),p=0;13>=p;p++)if(0!==p){var n=r.document.getElementById("OVVBeacon_"+p);if(!n.isViewable){b=null;break a}n=n.isViewable();if(e[p]=n)switch(b++,p){case 2:case 3:case 4:case 5:h++;break;case 6:case 7:case 8:case 9:c++;break;case 10:case 11:case 12:case 13:a++}}b=13===b?100:!1===e[1]?3<=a||3<=c||3<=h?null:0:!0===e[1]&&(!0===e[2]&&
!0===e[3]||!0===e[2]&&!0===e[4]||!0===e[3]&&!0===e[5]||!0===e[4]&&!0===e[5])||!0===e[1]&&4==c?50:e[2]&&e[5]&&!(e[6]&&e[10]&&e[1]&&e[13]&&e[9])||e[4]&&e[3]&&!(e[8]&&e[12]&&e[1]&&e[11]&&e[7])?null:0}return b}}
function X(b,f,d,l,k,u,r,q){this.b=new O;this.window=b;this.c=f;this.V=d;this.O=l;this.da=r&&r.Enums.BrowserId||window.$dv.Enums.BrowserId;this.fa=r&&r.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=k;this.wc=u;this.xa=this.S=null;this.nd=this.window?this.b.Ib(this.window.top):this.b.Ib(window.top);this.jf=this.V!=this.fa.CrossDomain&&this.b.cb("ofs")&&this.nd;this.S=new V(this.V,this.O,r,q);null!=this.S&&this.S.Ea()&&this.S.Ta(this.window,this.c);this.xa=new W(this.V,this.O,r);null!=
this.xa&&this.xa.Ac()&&this.xa.Ta(this.window,this.c);this.Eb=this.Kb=this.ta=null;this.kb=!1;var g=0;this.ka={he:1,ie:2,ce:4,Yb:8,be:16,Zb:32,ge:64};this.Gc=function(b,h,c,a){if(a&&a.insertBefore&&a.firstChild&&(b=this.window.document.createElement(b))){for(var e in h)b[e]=h[e];for(e in c)b.style[e]=c[e];a.insertBefore(b,a.firstChild);return b}return null};this.Je=function(b,h,c){var a=this.window.top,e=b.width,p=b.height;0>c.left?(e=b.width-Math.abs(c.left),0>h.Ha&&(e-=Math.abs(h.Ha))):0>h.Ha&&
(e=b.width-Math.abs(h.Ha)+c.left,e=e>b.width?b.width:e);var n=b.width,x=Math.min(this.b.Ca(a.window).clientWidth,a.innerWidth),g=screen.availWidth-x-h.Ha,f=0;e<n?(n=e,f=x-e,0>h.Ha&&(f-=Math.abs(h.Ha))):f=x-n-c.left;0>f?(e=n-Math.abs(f),0>g&&(e-=Math.abs(g))):0>g&&(e=n-Math.abs(g)+f,e=e>n?n:e);h=screen.availHeight-h.Nf-a.outerHeight;a=Math.min(this.b.Ca(a.window).clientHeight,a.innerHeight)-b.height-c.top;0>a?(p=b.height-Math.abs(a),0>h&&(p-=Math.abs(h))):0>h&&(p=b.height-Math.abs(h)+a,p=p>b.height?
b.height:p);0>c.top&&(p-=Math.abs(c.top));return{dg:e,eg:p}};this.qc=function(b,h,c,a){var e=c.C,p=c.B,n=0;c=0;var g={width:h.right-h.left,height:h.bottom-h.top};if(0>h.bottom||0>h.right||h.top>p||h.left>e||0>=g.width||0>=g.height)return 0;0>h.top?Math.abs(h.top)>=g.height?n=0:(n=g.height+h.top,n>p&&(n=p)):n=h.top+g.height>p?p-h.top:g.height;0>h.left?Math.abs(h.left)>=g.width?c=g.width:(c=g.width+h.left,c>e&&(c=e)):c=h.left+g.width>e?e-h.left:g.width;this.jf&&(b=this.Je(g,b,h),c=b.dg,n=b.eg);return 0>=
c||0>=n?0:Math.round(c*n/(g.width*g.height)*(a?g.width*g.height/((a.right-a.left)*(a.bottom-a.top)):1)*100)};this.jd=function(b,h){var c=h.C,a=h.B,e={pb:!0,qb:!0,Za:!0,$a:!0};try{if(0>b.top||b.top>a)e.qb=!1,e.pb=!1;if(0>b.bottom||b.bottom>a)e.$a=!1,e.Za=!1;if(0>b.left||b.left>c)e.pb=!1,e.Za=!1;if(0>b.right||b.right>c)e.qb=!1,e.$a=!1}catch(p){}return e};this.pc=function(b,h){try{var c={x:b.offsetLeft,y:b.offsetTop},a;b.offsetParent?(a=this.pc(b.offsetParent,h),c.x+=a.x,c.y+=a.y):h!=h.parent&&this.b.$b(h,
h.parent)&&(a=this.pc(h.frameElement,h.parent),c.x+=a.x,c.y+=a.y);return c}catch(e){return{x:null,y:null}}};var m=this.b.Gb();this.qa=function(b){if(this.V==this.fa.CrossDomain)if(this.b.za(this.window)&&this.window.$sf.ext.geom)this.qa=function(){var a=this.b.Ra(this.window),c=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):this.P.Explorer.ca,e={C:null,B:null,M:null,N:null,s:!1};e.C=parseInt(a.win.w);e.B=parseInt(a.win.h);e.M=parseInt(a.win.l);
e.N=parseInt(a.win.t)+c;e.s=!0;return e};else if(this.O.U==this.da.Firefox)this.qa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,c=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,e={C:null,B:null,M:null,N:null,s:!1};e.C=this.window.outerWidth;e.B=this.window.outerHeight-this.P.Firefox.ca;e.M=c;e.N=a+this.P.Firefox.ca;e.s=!0;return e};else if(this.b.yc(this.window)){var h=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){h.ta=
a})});this.qa=function(){var a={C:null,B:null,s:!1,M:null,N:null};null!=this.ta?(a.C=this.ta.rootBounds.width,a.B=this.ta.rootBounds.height):(a.C=0,a.B=0);a.s=!0;return a}}else if(this.O.U==this.da.IE&&10<=parseInt(this.O.pa))m&&this.Mb(),this.qa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,c=a?0:this.window.screenX,a=a?0:this.window.screenY,e={C:null,B:null,M:null,N:null,s:!1};e.C=this.window.outerWidth;e.B=this.window.outerHeight-this.P.Explorer.ca;e.M=c;e.N=a+this.P.Explorer.ca;
m?(this.kb||this.Mb(),e.s=!1):e.s=!0;return e};else if(this.O.U==this.da.IE&&/[6-9]|[10]/.test(this.O.pa)){var c=this.Gc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,Ee:0,sf:"0",tf:"0"},{display:"inline",position:"absolute",top:0,left:0,cg:"none",zIndex:0,border:0},this.window.document.body),a=this.Gc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,Ee:0,sf:"0",tf:"0"},{display:"inline",position:"absolute",top:0,left:0,cg:"none",zIndex:0,border:0},this.window.document.body),e=a.contentWindow||
a.window||a.contentDocument.window||a.contentWindow.window||this.window.gg,p=c.contentDocument||c.contentWindow.document,c=a.contentDocument||a.contentWindow.document,n="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.bb={bc:window.event.clientY,ac:window.event.clientX,Vd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",a='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+
function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.ua={bc:window.event.clientY,ac:window.event.clientX,Ma:window.event.screenY-window.event.y,La:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";c.open("text/html","replace");c.write(a);c.close();p.open("text/html","replace");p.write(n);p.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.qa=function(){e.runMoM();
p.open("text/html","replace");p.write(n);p.close();var a=this.window.ua,c=this.window.bb,b=screen.availWidth,h=screen.availHeight,c=c?c.Vd:this.P.Explorer.ca;if(a){var g=a.La,f=a.Ma;a.La>=b&&(a.La-=b);a.Ma>=h&&(a.Ma-=h);var d={C:null,B:null,M:null,N:null,s:!1};d.C=this.window.outerWidth?this.window.outerWidth-20:b-a.La-20;d.B=this.window.outerHeight?this.window.outerHeight-c-10:h-a.Ma-10;d.M=g;d.N=f;d.s=!0}else d={C:null,B:null,M:null,N:null,s:!1},d.C=this.window.outerWidth?this.window.outerWidth-
20:b-20,d.B=this.window.outerHeight?this.window.outerHeight-c-10:h-10,d.M=null,d.N=null,d.s=!1;return d}}else this.b.Gb()?(this.Mb(),this.qa=function(){this.kb||this.Mb();var a={C:null,B:null,M:null,N:null,s:!1};a.C=this.window.outerWidth;a.B=this.window.outerHeight-this.P.Chrome.ca;a.s=!1;return a}):this.qa=this.O.U==this.da.Chrome?function(){var a={C:null,B:null,M:null,N:null,s:!1},c=!1;try{a.C=this.window.frameElement.offsetParent.parentNode.clientWidth,a.B=this.window.frameElement.offsetParent.parentNode.clientHeight,
c=!0}catch(e){}a.M=this.window.screenX;a.N=this.window.screenY;a.s=c;return a}:null!=this.S&&this.S.Ea()?function(){var a={C:null,B:null,M:null,N:null,s:!1};a.C=this.window.outerWidth;a.B=this.window.outerHeight-this.P.Safari.ca;a.s=!1;return a}:function(){return{C:null,B:null,M:null,N:null,s:!1}};else this.qa=function(){var a,c,e=this.window.top;void 0!=e.mozInnerScreenX&&null!=e.mozInnerScreenX?(a=e.mozInnerScreenX,c=e.mozInnerScreenY):void 0!=e.screenX&&null!=e.screenX?0!=e.screenLeft+8&&e.screenLeft+
8!=screen.width||0!=e.screenTop+8&&e.screenTop+8!=screen.height?(a=e.screenLeft,c=e.screenTop+(e.outerHeight-e.innerHeight)):(a=e.screenLeft+8,c=e.screenTop+(e.outerHeight-e.innerHeight)+8):(a=e.screenLeft,c=e.screenTop);var b={C:null,B:null,M:null,N:null,s:!1},p=this.b.Ca(e);b.C=e.innerWidth||p.clientWidth;b.B=e.innerHeight||p.clientHeight;b.M=a;b.N=c;b.s=!0;return b};return this.qa(b)};this.ma=function(b,h){g=1;this.V==this.fa.CrossDomain?this.b.za(this.window)&&this.window.$sf.ext.geom&&this.b.Ra(this.window).par?
(g=8,this.ma=function(){var c=this.b.Ra(this.window),a=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(c.win.h):this.P.Explorer.ca,e={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};e.A=parseInt(c.self.l)-parseInt(c.par.l);e.v=parseInt(c.self.t)-parseInt(c.par.t);e.K=parseInt(c.self.l);e.L=parseInt(c.self.t);e.D=parseInt(c.win.l)+e.A;e.F=parseInt(c.win.t)+e.v+a;e.o=parseInt(c.self.w);e.j=parseInt(c.self.h);
e.s=!0;e.rect={top:e.v,bottom:e.v+e.j,left:e.A,right:e.A+e.o};return e}):this.O.U==this.da.Firefox?this.ma=function(){var c=1;window.devicePixelRatio&&(c=window.devicePixelRatio);var a=this.window.screenX,e=this.window.screenY,b=this.window.mozInnerScreenX/c-a,c=this.window.mozInnerScreenY/c-e-this.P.Firefox.ca,b={left:b,top:c,right:b+this.window.innerWidth,bottom:c+this.window.innerHeight},c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};c.A=b.left;c.v=b.top;
c.K=null;c.L=null;c.D=a+b.left;c.F=e+b.top;c.o=this.window.innerWidth;c.j=this.window.innerHeight;c.s=!0;c.rect=b;this.b.Sb()&&(c=this.Ab(c));return c}:this.b.yc(this.window)?(g=32,this.ma=function(){var c={A:null,v:null,o:null,j:null,s:!1,rect:null,R:null,na:null,K:null,L:null,D:null,F:null};null!=this.ta?(c.A=this.ta.boundingClientRect.left,c.v=this.ta.boundingClientRect.top,c.o=this.ta.boundingClientRect.width,c.j=this.ta.boundingClientRect.height):(c.A=0,c.v=0,c.o=0,c.j=0);c.s=!0;c.rect={top:c.v,
bottom:c.v+c.j,left:c.A,right:c.A+c.o};return c}):null!=this.xa&&this.xa.Ac()?this.ma=function(){var c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};null!=this.c&&(adData=this.b.eb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.j=adData?adData.h:this.window.innerHeight);return c}:this.O.U==this.da.IE&&10<=parseInt(this.O.pa)?this.ma=function(c){var a=this.window.screenLeft-window.screenX,e=this.window.screenTop-window.screenY-this.P.Explorer.ca,a={left:a,
top:e,right:a+this.window.innerWidth,bottom:e+this.window.innerHeight},e={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};e.A=a.left;e.v=a.top;e.K=null;e.L=null;e.D=c.M+a.left;e.F=c.N+a.top;e.o=this.window.innerWidth;e.j=this.window.innerHeight;e.s=!m;e.rect=a;this.b.Sb()&&(e=this.Ab(e));return e}:this.O.U==this.da.IE&&/[6-9]|[10]/.test(this.O.pa)?this.ma=function(){if(8==document.documentMode)return{A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,
rect:null,R:null,na:null};var c=this.window.bb&&this.window.ua?this.window.bb.bc-this.window.ua.bc:0,a=this.window.bb&&this.window.ua?this.window.bb.ac-this.window.ua.ac:0,e=this.b.Ca(this.window),b={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};b.A=a;b.v=c;b.K=null;b.L=null;b.D=this.window.ua?a+this.window.ua.La:null;b.F=this.window.ua?c+this.window.ua.Ma:null;b.o=this.window.innerWidth||e.clientWidth;b.j=this.window.innerHeight||e.clientHeight;b.s=!0;b.rect=
{left:a,top:c,right:a+(this.window.innerWidth||e.clientWidth),bottom:c+(this.window.innerHeight||e.clientHeight)};this.b.Sb()&&(b=this.Ab(b));return b}:this.b.Gb()?(g=512,this.ma=function(){var c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};null!=this.c&&(adData=this.b.eb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.j=adData?adData.h:this.window.innerHeight);return c}):this.ma=this.O.U==this.da.Chrome?function(){var c=null,a=null,e=!1;try{var b=this.window.frameElement.offsetTop,
c=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,a=b-this.window.frameElement.offsetParent.scrollTop,e=!0}catch(n){}b={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};b.A=c;b.v=a;b.K=null;b.L=null;b.D=null;b.F=null;b.o=this.window.innerWidth;b.j=this.window.innerHeight;b.s=e;b.rect=e?{left:c,top:a,right:c+this.window.innerWidth,bottom:a+this.window.innerHeight}:null;this.b.Sb()&&(b=this.Ab(b));return b}:null!=this.S&&this.S.Ea()?
function(){var c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};null!=this.c&&(adData=this.b.eb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.j=adData?adData.h:this.window.innerHeight);return c}:function(){return{A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null}}:this.ma=function(c){var a=this.pc(this.c,this.window),e={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null},b=this.b.sc(this.c,
this.window),n=this.b.Mc(this.c,this.window);e.A=n.left;e.v=n.top;e.K=a.x;e.L=a.y;e.D=c.M+n.left;e.F=c.N+n.top;e.o=n.w;e.j=n.h;e.s=!0;e.rect=b;e.R=n;return e};return this.ma(b,h)};this.Ab=function(b){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return b;var h=this.b.eb(this.c);if(h){var c=h.w,a=h.h,e=b.A,p=b.v,n=b.F,g=b.D;null!=b.A&&null!=b.v&&null!=b.j&&null!=b.o&&b.rect&&(0<h.t?(p=b.v+h.t,null!=b.F&&(n=b.F+h.t)):a+=h.t,0<h.l?(e+=h.l,null!=b.D&&(g=b.D+h.l)):
c+=h.l,h.r>b.o&&(c-=h.r-b.o),h.Vc>b.j&&(a-=h.Vc-b.j),b.o=0<c?c:0,b.j=0<a?a:0,b.A=e,b.v=p,b.F=n,b.D=g,b.rect.left=b.A,b.rect.top=b.v,b.rect.right=b.A+h.w,b.rect.bottom=b.v+h.h,b.R={w:c,h:a,left:e,right:e+c,top:p,bottom:p+a})}return b};this.$e=function(){var b=screen.availWidth,h=screen.availHeight,c=screen.width,a=screen.height,e=0,p=0;this.nd&&(p=this.window.top,e=p.screenX,p=p.screenY);return{s:this.P.Da?!1:"undefined"!==typeof e,Ob:b||c,Nb:h||a,mg:e,ng:p,Ha:e-(c-b),Nf:p-(a-h)}};this.He=function(){var b=
this.$e(),h=this.qa(b),c=this.ma(h,b);return{$:h,f:c,Aa:b,Tb:(null==h.M||null==h.N?0:this.ka.he)|(null==h.C||null==h.B?0:this.ka.ie)|(null==c.A||null==c.v?0:this.ka.ce)|(null==c.K||null==c.L?0:this.ka.Yb)|(null==c.D||null==c.F?0:this.ka.be)|(null==c.j||null==c.o?0:this.ka.Zb)|(null==b.Nb||null==b.Ob?0:this.ka.ge),H:this.ad(c.j,c.o)}};this.ad=function(b,h){null==b&&(b=0);null==h&&(h=0);return 1!=this.P.Da?242500<=b*h:!1};this.Qe=function(){this.b.a("c10");if(null!=this.c)if(this.b.sd(this.c,this.window))try{var b=
{timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:0};if(!this.wc())return b;var h=this.He(),c,a=h.f,e=h.$;c=a&&a.o&&a.j&&e&&e.C&&e.B?a.o>e.C||a.j>e.B:!1;var p;if(!h.f.s||!h.$.s){if(this.b.za(this.window)&&this.window.$sf.ext.inViewPercentage){p=this.window.$sf.ext.inViewPercentage();if(this.P.Da&&c&&this.S.Ea()){var n={timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:2};if(0==this.S.Dc())n.g=-6,n.W=-6,this.S.Ta(this.window,this.c);else{var d=this.S.ib();if(null!=d)var f=d.Y}}return{timeStamp:new Date,g:p,W:p,
u:h,H:h.H,aa:16,Na:c,Y:f}}if(m&&this.kb){p=0;null!=this.Eb&&(p=Math.round(100*this.Eb.intersectionRatio));var k=this.ad(h.f.j,h.f.o);this.P.Da&&c&&this.S.Ea()&&(n={timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:2},0==this.S.Dc()?(n.g=-6,n.W=-6,this.S.Ta(this.window,this.c)):(d=this.S.ib(),null!=d&&(f=d.Y)));return{timeStamp:new Date,g:p,W:p,u:h,H:k,Na:c,aa:512,Y:f}}if(this.xa.Ac()){var l={timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:64},d=this.xa.ib();null!=d&&(l.u=h,l.H=h.H,l.g=d,l.W=d,l.Na=c);return l}if(this.S.Ea())return n=
{timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:2},0==this.S.Dc()?(n.g=-6,n.W=-6,this.S.Ta(this.window,this.c)):(d=this.S.ib(),null!=d&&(n.u=h,n.H=h.H,n.g=d.sa,n.W=d.sa,n.Na=c,n.Y=d.Y)),n;b.u=h;g&&(b.aa=g);return b}if(h.f&&h.f.R&&(0===h.f.R.w||1===h.f.R.w||0===h.f.R.h||1===h.f.R.h))return{timeStamp:new Date,g:-5,W:-5,u:h,aa:g};h.f.R?(p=this.qc(h.Aa,h.f.R,h.$,h.f.rect),f=this.jd(h.f.R,h.$)):(p=this.qc(h.Aa,h.f.rect,h.$),f=this.jd(h.f.rect,h.$));return{timeStamp:new Date,g:p,W:p,u:h,H:h.H,aa:g,Y:f,Na:c}}catch(q){return{timeStamp:new Date,
g:-4,W:-4,u:null,H:!1,aa:g}}else return{timeStamp:new Date,g:-2,W:-2,u:null,H:!1,aa:0};else return{timeStamp:new Date,g:-1,W:-1,u:null,H:!1,aa:0}};this.Ie=function(b,h){this.b.a("c11");var c=null,a=null;if(null!=b.u){var e=b.u.f;h<=this.P.zf&&(c=0<=b.g||-5==b.g?b.H&&b.g>=this.P.lb||0==b.H&&50<=b.g?!0:!1:null,a=b.H?this.P.lb/100:.5,a=0==c?0>e.v+e.j*a?!0:!1:1==c?!1:null)}return{pd:a,qd:c}};this.Fb=function(b){this.b.a("c12");var h=null;if(2!=b.aa&&512!=b.aa&&null!=b.u){var c=b.u.Tb,a=b.u.f;(c&this.ka.Yb)==
this.ka.Yb&&(c&this.ka.Zb)==this.ka.Zb&&(h=this.qc(b.u.Aa,{left:a.K,top:a.L,right:a.K+a.o,bottom:a.L+a.j},b.u.$,a.rect),h=0<=b.g?b.H&&h>=this.P.lb||0==b.H&&50<=h?!1:!0:null)}this.b.a("c12e");return h};this.Mb=function(){function b(c){c.forEach(function(a){h.Eb=a})}var h=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(g=512,this.Kb=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.Kb.observe(this.c),this.kb=!0)};this.ef=function(){this.c=null;null!=this.Kb&&
(this.Kb.disconnect(),this.Eb=null,this.kb=!1)}}
function O(){this.getElementVolume_object=function(b){var f=b.getAttribute("width"),d=b.getAttribute("height");null==f||""==f||null==d||""==d?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:f,h:d};return b};this.nf=function(b){var f=0;try{for(;null!=b&&10>f;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;f++}}catch(d){}return!0};this.ia=function(b,f){this.a("cm1");var d=null,l=b.nodeName.toLowerCase();f&&this["getElementVolume_"+
l]&&(d=this["getElementVolume_"+l](b));if(!d&&(d=this.eb(b),this.a("cm2e"),!d||1>=d.w||1>=d.h))return this.a("cm1e"),{w:0,h:0};d.w.indexOf&&d.w.indexOf("px")&&(d.w=d.w.replace("px",""));d.h.indexOf&&d.h.indexOf("px")&&(d.h=d.h.replace("px",""));this.a("cm1e");return d};this.eb=function(b){this.a("cm2");try{var f;return document.body.getBoundingClientRect&&(f=b.getBoundingClientRect())?{w:f.right-f.left,h:f.bottom-f.top,l:f.left,t:f.top,Vc:f.bottom,r:f.right}:null}catch(d){return null}};this.Ca=function(b){return b.document.documentElement.clientHeight?
b.document.documentElement:b.document.body};this.gd=function(b,f){this.a("ff9");var d=0,l=!1;if(b.document.all)for(var k=0;k<b.document.all.length;k++)"BODY"==b.document.all[k].nodeName&&(l=!0),l&&("width"==f?b.document.all[k].width>d&&(d=b.document.all[k].width):b.document.all[k].height>d&&(d=b.document.all[k].height));this.a("ff9e");return d};this.vd=function(b,f){for(var d=this.Ca(b),l=b.innerWidth||d.clientWidth||this.gd(b,"width"),d=b.innerHeight||d.clientHeight||this.gd(b,"height"),k=f.length,
u=0,r=0;r<k;r++)if(15>=Math.abs(l-f[r].w)){u=f[r].h.length;for(l=0;l<u;l++)if(15>=Math.abs(d-f[r].h[l]))return!0;break}return!1};this.ag=function(b){for(var f=[],d=-1;f[++d]=b[d];);f.length--;return f};this.Vb=function(b,f,d,l,k,u,r){r=r||15;var q=b.getElementsByTagName("*"),q=this.ag(q);q.unshift(b);for(var g="EMBED IFRAME OBJECT IMG SPAN DIV SVG CANVAS".split(" "),m=[],w=0;w<q.length;w++){var h=q[w];if(-1!=g.indexOf(h.nodeName.toUpperCase())){var c=l(h);!c||k&&u&&(Math.abs(c.w-k)>r||Math.abs(c.h-
u)>r)||m.push({Uc:c.w*c.h,w:c.w,h:c.h,type:h.nodeName||"other",De:h})}}m=m.sort(function(a,c){return c.Uc-a.Uc||g.indexOf(c.type)-g.indexOf(a.type)});(f=0<m.length&&m[0].w>f&&m[0].h>d?m[0].De:null)&&b&&(f.Db=b.Db);return f};this.sd=function(b,f){this.a("ff10");try{if(!b)return!1;for(f||(f=window);b!=f.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==f.document}catch(d){return!1}};this.sc=function(b,f){var d=f.parent,l={left:0,right:0,top:0,bottom:0};if(b){var k=b.getBoundingClientRect();
f!=d&&this.$b(f,d)&&(l=this.sc(f.frameElement,d));l={left:k.left+l.left,right:k.right+l.left,top:k.top+l.top,bottom:k.bottom+l.top}}return l};this.$b=function(b,f){var d=!1;if(b==f)d=!0;else try{b.document.domain==f.document.domain&&(d=!0)}catch(l){}return d};this.Re=function(b){if(b)try{if(b.contentDocument&&this.rd(b.contentDocument))return b.contentDocument;if(b.contentWindow&&this.Ib(b.contentWindow))return b.contentWindow.document}catch(f){}return null};this.md=function(b){return b?b.defaultView||
b.parentWindow:null};this.hf=function(b,f){return-1<f.indexOf(b)};this.Ke=function(b){try{return b!=b.top&&b.parent&&this.Ib(b.parent)?b.parent:null}catch(f){return null}};this.Ib=function(b){try{return b&&b.document&&this.rd(b.document)?!0:!1}catch(f){return!1}};this.rd=function(b){try{return b&&b.getElementsByTagName&&b.getElementById?!0:!1}catch(f){return!1}};this.Mc=function(b,f){var d=f.parent,l={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(l=this.sc(b,f),l.w=l.right-l.left,l.h=l.bottom-l.top,
f!=d&&this.$b(f,d)&&(d=this.Mc(f.frameElement,d),d.bottom<l.bottom&&(d.bottom<l.top&&(l.top=d.bottom),l.bottom=d.bottom),d.top>l.top&&(d.top>l.bottom&&(l.bottom=d.top),l.top=d.top),d.right<l.right&&(d.right<l.left&&(l.left=d.right),l.right=d.right),d.left>l.left&&(d.left>l.right&&(l.right=d.left),l.left=d.left),l.w=l.right-l.left,l.h=l.bottom-l.top));return l};this.hc=function(b,f){return function(){return b.apply(f,arguments)}};this.ya=function(b){try{return b?b.length?b.length:0:0}catch(f){return 0}};
this.vc=function(b){for(var f=[],d=0;d<b.length;d++)this.nf(b[d])&&f.push(b[d]);return f};this.a=function(b){try{maxLength=3,$dv&&($dv.Sa=$dv.Sa||[],$dv.Sa.push(b),$dv.Sa.length>maxLength&&$dv.Sa.shift())}catch(f){}};this.Ue=function(){try{return $dv&&$dv.Sa?$dv.Sa.join():""}catch(b){return""}};this.za=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=this.Ra(b),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.za=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.za=
function(){return!1};return!1};this.Ra=function(b){b.$sf.ext.geom&&(this.Ra="function"==typeof b.$sf.ext.geom?function(b){return b.$sf.ext.geom()}:function(b){return b.$sf.ext.geom});return this.Ra(b)};this.G=function(b,f){if(null!=b&&null!=f)for(var d in f)f.hasOwnProperty(d)&&(b[d]=f[d])};this.yc=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.Gb=function(){var b=!1;if(1==this.cb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.Hb=function(b,
f,d){var l=d&&d.Enums.BrowserId||window.$dv.Enums.BrowserId;if(b==(d&&d.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&(!(f.U!==l.Safari&&7!=f.U||null!==f.pa&&void 0!==f.pa&&/^[3-8]/.test(f.pa))||(6==f.U||f.U==l.Chrome)&&(null===f.pa||45<f.pa)))return this.Hb=function(){return!0},!0;this.Hb=function(){return!1};return!1};this.Bc=function(b,f,d){var l=d&&d.Enums.BrowserId||window.$dv.Enums.BrowserId,k=$dv.tags[$uid].AVO&&$dv.tags[$uid].AVO.fls;if(b==(d&&d.Enums.TrafficScenario||
window.$dv.Enums.TrafficScenario).CrossDomain&&f.U===l.IE&&k)return this.Bc=function(){return!0},!0;this.Bc=function(){return!1};return!1};this.cb=function(b){var f,d=this.ed();d&&d.AVO&&(f=d.AVO[b]);return f};this.ed=function(){var b={},f=window.$dv,d=window.$uid;f.tags&&f.tags[d]&&(b=f.tags[d]);return b};this.Sb=function(){return 1==this.cb("sam")?!0:!1};this.hb=function(b){return b.document.hasFocus()};this.zb=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(f,d,l,k,
u){if("undefined"==typeof k||null==k)k=window;k.addEventListener(f,d,l);u&&b.cache.push([f,d,l,k])}:window.attachEvent?b.add=function(f,d,l,k,u){if("undefined"==typeof k||null==k)k=window;k["e"+f+d]=d;k[f+d]=function(){k["e"+f+d](window.event)};k.attachEvent("on"+f,k[f+d]);u&&b.cache.push([f,d,l,k])}:b.add=function(){};window.removeEventListener?b.remove=function(b,d,l,k){if("undefined"==typeof k||null==k)k=window;k.removeEventListener(b,d,l)}:window.detachEvent?b.remove=function(b,d,l,k){if("undefined"==
typeof k||null==k)k=window;k.detachEvent("on"+b,k[b+d]);k[b+d]=null;k["e"+b+d]=null}:b.remove=function(){};b.flush=function(){for(var f=0;f<b.cache.length;f++)b.remove.apply(b,b.cache[f]);b.cache=[]}};this.getElementsByClassName=function(b,f){return b.getElementsByClassName?b.getElementsByClassName(f):b.querySelectorAll?b.querySelectorAll("."+f):[]};this.Da=function(){var b=!1;if($dv&&$dv.CommonData){var f=$dv.CommonData.detectedDeliveryType;f&&0!=f?b=2==f||3==f:(f=$dv.CommonData.deviceType)&&(b=
2==f||3==f)}return b};this.Te=function(b,f){var d=b||"",l="";if(f&&(d+=": "+(f.message||""),f.stack)){var l=f.stack||"",k=l.indexOf("at ");0>k&&(k=0);l=", Stack: "+l.slice(k,l.length)}d=d.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");l=l.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");k=null;try{k=encodeURIComponent(d+l).slice(0,500)}catch(u){try{k=encodeURIComponent(d).slice(0,500)}catch(r){k=
d.slice(0,500)}}return k}}
function aa(b,f,d,l,k,u){function r(b){var c=[],a=null;b&&b.parentNode&&(a=b.parentNode.firstChild);for(;a;)1===a.nodeType&&a!==b&&c.push(a),a=a.nextElementSibling||a.nextSibling;return c}var q=new O;this.i=l;this.window=d;this.c=null;this.dataObj=b;this.dvObj=b.dvObj||window.$dv;this.xc=null;this.O={U:this.dvObj.CommonData.BrowserId,pa:this.dvObj.CommonData.BrowserVersion};this.da=this.dvObj.Enums.BrowserId;this.V=k;this.fa=this.dvObj.Enums.TrafficScenario;this.la=f;this.m=u.m;var g=0;115==this.dataObj.Pa&&
(this.m.J.h=20,this.m.J.w=20);this.Lf=function(){u.Ef(this.c);this.c=u.c=null};var m=[],w="object embed img iframe svg canvas".split(" ");this.dataObj.spotXmode&&(w=["object","embed","video","iframe"]);this.lf=function(b){q.a("a33");b=q.ia(b);var c=!1;return c=this.dataObj.Ec&&this.m.ha.h&&this.m.ha.w?this.bg(b,this.m.ha.w,this.m.ha.h):this.mf(b)};this.bg=function(b,c,a){var e=this.m.Ya||15;if(c&&a)return Math.abs(b.w-c)<=e&&Math.abs(b.h-a)<=e};this.mf=function(b){if(b){var c=b.w;b=b.h;for(var a=
this.m.Ya||15,e=f.length,p=0,n=0;n<e;n++)if(Math.abs(c-f[n].w)<=a)for(var p=f[n].h.length,g=0;g<p;g++)if(Math.abs(b-f[n].h[g])<=a)return!0}return!1};this.Oe=function(){q.a("a34");return this.Pe()||this.Of()};this.Of=function(){q.a("a35");var b=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),c=[],a=window.parent;q.a("ff6");try{c=a.document.getElementsByTagName("script")}catch(p){}q.a("ff6e");for(var a=c.length,e=0;e<a;e++)if(c[e]&&c[e].id&&c[e].id.substr(7)==b)return c[e];
return null};this.Pe=function(){q.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.oe=function(b){q.a("a38");var c={node:b,Ba:0};b=[];for(m=[];c||0<b.length;){try{var a;a:{var e=c.node;try{if(e&&-1!=w.indexOf(e.nodeName.toLowerCase())){a=!0;break a}}catch(g){}a=!1}if(a&&this.lf(c.node)&&!u.ra(c.node)&&u.T(c.node))return c;if(c.Ba<=this.m.vf){var p,n=c.node,d=c.Ba,c=[],
f=n.parentNode;f&&-1==m.indexOf(f)&&(m.push(f),c.push({node:f,Ba:d+1}));if(n.hasChildNodes())for(var k=0;k<n.childNodes.length;k++)n.childNodes[k]&&-1==m.indexOf(n.childNodes[k])&&1===n.childNodes[k].nodeType&&(m.push(n.childNodes[k]),c.push({node:n.childNodes[k],Ba:d+1}));for(var l=r(n),k=0;k<l.length;k++)l[k]&&-1==m.indexOf(l[k])&&1===l[k].nodeType&&(m.push(l[k]),c.push({node:l[k],Ba:d+1}));if(p=c)for(c=0;c<p.length;c++)b.push(p[c])}}catch(g){}c=b.shift()}return{node:null}};this.We=function(b){q.a("a37");
var c=null;b&&(c=this.oe(b));return c};this.Ne=function(b){b=r(b);g=1;for(var c=0;c<b.length;c++)if(b[c]&&-1==m.indexOf(b[c])&&1===b[c].nodeType&&u.zc(b[c])&&!u.ra(b[c])){var a=u.nc(b[c]);if(a){if(u.T(b[c]))return u.T(a),{node:a,Ba:1}}else g=4}};this.Fe=function(b){q.a("a31");if(this.c=u.Ve())return this.i.Td(),this.xc=!0,this.c;if(this.dataObj.btreg&&!0===this.xc&&1<b)return this.c;if("1"!=this.dataObj.displaynon){var c=this.Oe(),a;this.dataObj.Pa==u.$c&&(a=this.Ne(c));this.dataObj.Ec&&(g=3);!a&&
b>=g&&(a=this.We(c));a&&a.node&&(this.i.Sd(a.Ba),this.c=a.node)}return this.c};return this}
function ba(b,f,d,l,k,u){function r(c,a){for(var e=[],b=0;b<h.length;b++){var n=[],n=a(c,h[b]),g=m.ya(n);if(0!=g){var d=m.md(h[b]);if(null!=d)for(var f=0;f<g;f++)try{n[f].Db=d,e.push(n[f])}catch(k){}}}return e}function q(c,a){return r(c,function(c,b){m.a("ff4");var g=b.getElementsByTagName(c);m.a("ff4e");return"1"!=a?g:m.vc(g)})}var g=this,m=new O,w="Microsoft Internet Explorer"==navigator.appName;this.dataObj=b;this.window=f;this.c=d;this.V=l;this.fa=k;this.dvObj=void 0===u?u={}:u;this.m={J:{h:1,
w:1},ha:{h:0,w:0},Ya:15,vf:10};this.$c="179";115==this.dataObj.Pa&&(this.m.J.h=20,this.m.J.w=20);this.dataObj.Ec&&this.dataObj.Hd&&this.dataObj.Gd&&(this.m.ha.h=this.dataObj.Gd,this.m.ha.w=this.dataObj.Hd);this.Ze=function(c){if(c.scanOrder)return c.scanOrder;var a=[1==w?"object":"embed",1==w?"embed":"object","href","img","span","iframe","frameElement","div","canvas","svg"];c.findclass&&1==c.findclass&&a.push("classDeclaration");c.vb&&0<c.vb.length&&a.unshift("searchCustomElementsFromTag");return a};
this.searchCustomElementsFromTag=function(c){for(var a=0;a<c.vb.length&&(g.bd(c.vb[a],c),!g.c);a++);};this.Ub=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.xe=function(){var c=g.dataObj.yb+"-"+g.dataObj.xb;b.isBrandShieldOrigin&&(c+="-bs");return c.replace(RegExp(",","g"),";")};this.Ic=this.xe();this.bd=function(c,a){if(a.btreg)for(var e=q(c,a.displaynon),b=m.ya(e),n=0;n<b;n++)if(e[n]&&g.Ia(a,e[n],!0)&&
!g.ra(e[n])){var d=this.zc(e[n])?this.nc(e[n]):null;if(d&&(f=m.ia(d))&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(d)){g.c=d;g.T(e[n]);break}var f=m.ia(e[n]);if(f&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(e[n])){g.c=e[n];break}if((d=m.Vb(e[n],g.m.J.w,g.m.J.h,m.hc(m.ia,m),this.m.ha.w,this.m.ha.h,this.m.Ya))&&g.T(d)){g.c=d;g.T(e[n]);break}}};this.div=function(c){this.bd("div",c)};this.span=function(c){m.a("a10");if(c.btreg)for(var a=q("span",c.displaynon),e=m.ya(a),b=0;b<e;b++)if(a[b]&&g.Ia(c,a[b],!0)&&!g.ra(a[b])){var d=a[b];
m.a("a20");if(d&&"1"==d.getAttribute("adunit")){g.c=a[b];break}if(d=this.zc(a[b])?this.nc(a[b]):null){var f=m.ia(d);if(f&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(d)){g.c=d;g.T(a[b]);break}}if((d=m.Vb(a[b],g.m.J.w,g.m.J.h,m.hc(m.ia,m),this.m.ha.w,this.m.ha.h,this.m.Ya))&&g.T(d)){g.c=d;g.T(a[b]);break}}};this.object=function(c){m.a("a11");for(var a=q("object",c.displaynon),b=m.ya(a),p=0;p<b;p++)if(a[p]&&g.Ia(c,a[p])&&!g.ra(a[p])){var d=m.Vb(a[p],g.m.J.w,g.m.J.h,m.hc(m.ia,m),this.m.ha.w,this.m.ha.h,this.m.Ya);
if(d&&g.T(d)){g.T(a[p]);g.c=d;break}}};this.tc=function(c,a){m.a("a14");for(var b=q(a,c.displaynon),p=m.ya(b),d=0;d<p;d++)if(b[d]&&g.Ia(c,b[d])&&!g.ra(b[d])){var f=m.ia(b[d]);if(f&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(b[d])){g.c=b[d];break}}};this.embed=function(c){m.a("a12");this.tc(c,"embed")};this.href=function(c){m.a("a13");for(var a=q("a",c.displaynon),b=m.ya(a),d=0;d<b;d++)if(a[d]&&g.Ia(c,a[d])&&!g.ra(a[d])){var f=a[d].getElementsByTagName("img");if(0<f.length){var h=m.ia(f[0]);if(h&&h.h>g.m.J.h&&
h.w>g.m.J.w&&g.T(a[d])){g.c=f[0];break}}}};this.img=function(c){m.a("a31");this.tc(c,"img")};this.canvas=function(c){m.a("a32");this.tc(c,"canvas")};this.classDeclaration=function(c){m.a("a9");var a="undefined"!==typeof window.document.getElementsByClassName,b="undefined"!==typeof window.document.querySelectorAll;if(c.btreg){var d=[];if(a)d=g.getElementsByClassName(c.btreg,c.displaynon);else if(b)d=g.querySelectorAll(c.btreg,c.displaynon);else return;c=m.ya(d);for(a=0;a<c;a++)if(d[a]&&!g.ra(d[a])&&
(b=m.ia(d[a]))&&b.h>g.m.J.h&&b.w>g.m.J.w&&g.T(d[a])){g.c=d[a];break}}};this.iframe=function(b){m.a("a15");for(var a=q("iframe",b.displaynon),e=m.ya(a),d=0;d<e&&!g.Qc(b,a[d]);d++);};this.frameElement=function(b){try{m.a("a16"),l==k.SameDomain&&g.Qc(b,window.frameElement)}catch(a){}};this.getElementsByClassName=function(b,a){return r(b,function(b,c){m.a("ff1");var d=c.getElementsByClassName(b);m.a("ff1e");return"1"!=a?d:m.vc(d)})};this.querySelectorAll=function(b,a){return r(b,function(b,c){m.a("ff3");
var d=c.querySelectorAll("."+b);m.a("ff3e");return"1"!=a?d:m.vc(d)})};this.oa=function(b,a){m.a("a28");return!b||!a||5>a.length?!1:null!=(g.Nc?g.Nc(b,a):g.Wb(b,a))?!0:g.jc&&"function"===typeof g.jc?g.jc(b,a):!1};this.Ia=function(b,a,e){m.a("a22");var d=null;return b.btreg&&(g.Nc=1==b.pf?g.Zd:g.Wb,d=g.ee(b,a,e))||!g.c&&(d=g.fe(b,a))?!0:!1};this.je=function(b){m.a("a21");if(b&&!g.ra(b)){var a=m.ia(b);if(a&&a.h>g.m.J.h&&a.w>g.m.J.w&&g.T(b))return g.c=b,!0}return!1};this.Qc=function(b,a){m.a("a17");return g.Ia(b,
a)?g.je(a):!1};this.ra=function(b){m.a("a19");if(b&&(b=b.getAttribute("dvvisit"))){b=b.split(",");for(var a=0;a<b.length;a++)if(b[a]==g.Ic)return!0}return!1};this.T=function(b){m.a("a18");if(b&&0==g.ra(b))try{var a=b.getAttribute("dvvisit");a?b.setAttribute("dvvisit",a+","+g.Ic):(m.a("ff5"),a=window.document.createAttribute("dvvisit"),m.a("ff5e"),a.value=g.Ic,b.setAttributeNode(a));$dv.eventBus&&window&&$dv.eventBus.dispatchEvent(window,"adLocated",{adElement:b,timeStamp:(new Date).getTime()});return!0}catch(e){}return!1};
this.Ef=function(b){b&&b.hasAttribute&&b.hasAttribute("dvvisit")&&b.removeAttribute("dvvisit")};this.Zd=function(b,a){m.a("a29");var e;try{e=(new RegExp(a)).exec(b)}catch(d){e=g.Wb(b,a)}return e};this.Wb=function(b,a){m.a("a30");var e=null;-1!==b.indexOf(a)&&(e=b);return e};this.zc=function(b){return this.dataObj.Pa==this.$c&&0==b.className.indexOf("celtra-ad-v")?!0:!1};this.nc=function(b){var a=null;b.celtra&&1==b.celtra.loaded&&(a=b.celtra.viewabilityObservee);a&&(a.Db=m.md(a.ownerDocument)||window);
return a};var h=[];this.ee=function(b,a,e){m.a("a23");var d;try{if(b.Yc&&a&&a.hasAttribute&&a.hasAttribute("dv-view"))return!0;(d=g.oa(a.id,b.btreg))||(d=g.oa(a.src,b.btreg));d||(d=g.oa(a.href,b.btreg));d||(d=g.oa(a.getAttribute("flashvars"),b.btreg));d||(d=g.oa(a.name,b.btreg));!d&&b.findclass&&1==b.findclass&&(d=g.oa(a.getAttribute("class"),b.btreg));if(!d&&g.dataObj.Qa&&0<g.dataObj.Qa.length)for(var f=g.dataObj.Qa,h=0;h<f.length&&!(d=g.oa(a.getAttribute(f[h]),b.btreg));h++);d||e||(d=g.oa(a.innerHTML,
b.btreg));d&&!e&&(d=g.de(b,a));return d}catch(k){return d}};this.Ja=function(b,a){m.a("a25");if(!b)return!1;b=b.toLowerCase();for(var e=0;e<g.Ub.length;e++){var d;if(a.Tc&&(d=(g.Ub[e][0]+a.Tc).toLowerCase(),d=b.indexOf(d),-1<d)||a.Bd&&(d=(g.Ub[e][0]+a.Bd).toLowerCase(),d=b.indexOf(d),-1<d))return!0}return!1};this.fe=function(b,a){m.a("a24");var e;try{if(b.Yc&&a&&a.hasAttribute&&a.hasAttribute("dv-view"))return!0;(e=g.Ja(a.id,b))||(e=g.Ja(a.src,b));e||(e=g.Ja(a.href,b));e||(e=g.Ja(a.jg,b));e||(e=g.Ja(a.name,
b));e||(e=g.Ja(a.innerHTML,b));if(!e&&g.dataObj.Qa&&0<g.dataObj.Qa.length)for(var d=g.dataObj.Qa,f=0;f<d.length&&!(e=g.oa(a.getAttribute(d[f]),b.btreg));f++);return e}catch(h){return e}};this.de=function(b,a){m.a("a26");return null==b.ab||""==b.ab?!1:g.oa(g.Yd(a),b.ab)};this.searchByAdSrvId_8=function(b,a){m.a("a1");var e=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(b);return null!=e&&(e=e.toString(),e.replace(RegExp("-","g"),"")==a)?!0:!1};this.jc=this["searchByAdSrvId_"+(g.dataObj?g.dataObj.Pa||"":"")];this.Yd=
function(b){m.a("a27");if(b.outerHTML)return b.outerHTML;for(var a=b.attributes.length,e="",d=0;d<a;d++)e=e+b.attributes[d].nodeName+"="+b.attributes[d].nodeValue+" ";return e+b.innerHTML};this.Ve=function(){m.a("32");var b=[];void 0===u.tags&&(u.tags={});void 0===u.tags[$uid]&&(u.tags[$uid]={});void 0!==u.tags[$uid].spvi&&(b.push(u.tags[$uid].spvi),-1<b[0].scanOrder.indexOf(",")&&(b[0].scanOrder=b[0].scanOrder.split(",")));g.dataObj.scanOrder=this.Ze(g.dataObj);b.push(g.dataObj);var a=g.window,e=
0,f=[];try{do{f.push(a.document);for(var n=f,k=a.document.getElementsByTagName("iframe")||[],l=0;l<k.length&&25>l;l++){var q=null,q=m.Re(k[l]);void 0!==q&&null!==q&&0==m.hf(q,n)&&n.push(q)}a=m.Ke(a)}while(a&&10>++e)}catch(r){}h=f;for(a=0;a<b.length;a++)for(e=b[a],f=0;f<e.scanOrder.length;f++)if(void 0!=g[e.scanOrder[f]]&&(g[e.scanOrder[f]](e),g.c))return g.c;return d};return this}
function dv_CustomClientViewAssureService(b){function f(b){return{Kf:{adView:b.rq.av,gf:b.rq.ic,Rc:b.rq.adc,uf:b.rq.mla,xd:b.rq.ldav,focus:b.rq.fc,Sc:b.rq.as,cc:b.rq.exp},Jf:{zd:d(b.rp.mt),Df:d(b.rp.pt),wf:d(b.rp.mr),Cf:d(b.rp.pr),eventId:b.rp.eid,Xc:b.rp.bl}}}function d(b){return"string"==typeof b?Array(b):b}this.ne=dv_InViewService;this.ne(b);this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this.b=new O;this.rb=[];b=$dv.tags[$uid].dc||b.dc||[];var l=this.b.ed().bgm,k;
for(k in b)b.hasOwnProperty(k)&&this.rb.push(new window.oc.ye(f(b[k]),l));var u=this.Xb;this.Xb=function(b){b=u(b);for(var d=0;d<this.rb.length;d++)this.rb[d].Ae(b,this.ba.interval);return b};var r=this.Wa;this.Wa=function(b,d){var f={};r(b,d);if(1==this.kc){for(var k=0;k<this.rb.length;k++){var h=this.rb[k].yf(),c;for(c in h)h.hasOwnProperty(c)&&(f[c]=h[c])}$dv.registerEventCall($uid,f)}}}window.oc=window.oc||{};
window.oc.ye=function(b,f){function d(a){a.u&&a.u.f&&a.u.f.j&&a.u.f.o&&242500<=a.u.f.o*a.u.f.j&&(u=!0,l.xd&&(l.adView=l.xd),d=function(){})}var l=b.Kf,k=b.Jf,u=!1,r=!1,q=!1,g=!1,m=!1,w=!1,h=!1;l.cc&&$dv.registerEventCall($uid,{dvp_ex:0});this.Ae=function(a,b){d(a);var f=!0,k;k=l.focus?a.g:a.W;l.adView&&l.adView>k&&(f=!1);l.Sc&&a.u&&a.u.f&&a.u.f.j&&a.u.f.o&&a.u.f.o*a.u.f.j<l.Sc&&(f=!1);f?c+=b:l.gf&&(c=0);l.cc&&!r&&(!a.Na&&98<=k&&($dv.registerEventCall($uid,{dvp_ex:1}),r=!0),a.Y&&(m=m||a.Y.qb,g=g||
a.Y.pb,h=h||a.Y.$a,w=w||a.Y.Za,m&&g&&h&&w&&(r=!0,$dv.registerEventCall($uid,{dvp_ex:2}))),a.Na&&!a.Y&&(r=!0,$dv.registerEventCall($uid,{dvp_ex:3})));this.se(a)};var c=0;this.yf=function(){return this.Gf(k.zd,k.wf,k.Xc)};this.Ed=function(){this.Hf(k.zd,k.Df,k.Cf,k.Xc,k.eventId);this.Ed=function(){}};this.se=function(a){if(l.Rc&&c>=l.Rc||u&&l.uf)q=!0;!q||l.cc&&!r||this.Ed(a)};var a;this.Gf=function(b,c,d){var g={};if(f&&d)return g;if(b)for(a=$dv.tags[$uid].getTimeDiff(),d=0;d<b.length;d++)g[b[d]]=a;
if(c)for(d=0;d<c.length;d++)$dv.pubSub.publish(c[d],$uid),window&&$dv.pubSub.publish(c[d],window.$frmId);return g};this.Hf=function(b,c,d,g,h){if(!f||!g){if(c){g={};for(var k=$dv.tags[$uid].getTimeDiff(),l=0;l<c.length;l++)g[c[l]]=k;h&&(g.evid=h);if(b)for(l=0;l<b.length;l++)g[b[l]]=a||$dv.tags[$uid].getTimeDiff();$dv.registerEventCall($uid,g)}if(d)for(l=0;l<d.length;l++)$dv.pubSub.publish(d[l],$uid),window&&$dv.pubSub.publish(d[l],window.$frmId)}}};
function ca(){var b=!1,f=!1,d=0,l=0,k=!1;this.update=function(u,r,q,g){k||(r?(b=!0,0<q?(f=!0,q>=(u?30:50)?(l+=g,d+=g,1E3<=d&&(k=!0)):d=0):d=0):d=0)};this.Ye=function(){return k?6:b?f?0==l?3:1E3>l?4:1E3>d?5:6:2:1}}
function dv_InViewService(b){function f(){null===k.interval&&(k.interval=setInterval(k.Se(),k.ba.interval))}function d(){if(!1===k.ud){k.ud=!0;try{k.b.zb.remove("load",arguments.callee,!1,element)}catch(a){}k.Pb();k.b.a("s41");k.va=new X(k.re?k.re:k.window,k.c,k.V,k.O,k.P,k.i.Zc,k.dvObj,k.impressionId);k.b.a("s42");k.ae();k.start()}}function l(a,b){return a.isReportingDisabled?new S:new R(a,b)}var k=this;this.yd=10;this.me=b.serverSettings&&b.serverSettings.jsVersion?b.serverSettings.jsVersion:"697";
this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this._minor_version="0";this.b=new O;this.df=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.ud=!1;this.Ad=new ca;this.bf=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=
a.substring(a.indexOf("?")+1));return a};this.ld=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.X=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.cf=function(){var a=this.X("uid",this.ea);null==a?(a=this.ld(),this.ea=this.ea+"&uid="+a):""==a&&(a=this.ld(),this.ea=this.ea.replace("&uid=","&uid="+a));return a};this.Gc=function(a,b,c,d){if(d&&d.insertBefore&&d.firstChild&&
(a=this.window.document.createElement(a))){for(var f in b)a[f]=b[f];for(f in c)a.style[f]=c[f];d.insertBefore(a,d.firstChild);return a}return null};this.qe=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.V=this.dvObj.CommonData.Scenario||this.qe();this.O={U:this.dvObj.CommonData.BrowserId,pa:this.dvObj.CommonData.BrowserVersion};this.da=this.dvObj.Enums.BrowserId;
this.fa=this.dvObj.Enums.TrafficScenario;this.mb="default";this.dataObj=b;this.window=b.tagWindow||parent.window||window;this.c=null;this.Kc=this.Xa=!1;this.Cc=!0;this.interval=null;this.ea=this.df();this.wa=this.bf();b.serverSettings&&b.serverSettings.protocol&&b.serverSettings.protocol.indexOf("http");this.ba=window.Ce||this.window.Ce||{interval:100,Ga:{"default":{time:null,zb:["beforeunload","unload"],Od:84E4}}};this.Dd={};var u=null,r=1==this.b.cb("int");this.I=window.Be||this.window.Be||{interval:r?
100:1E3,Z:r?60:6};r=b&&b.Qd?b.Qd:!1;b=b&&b.Rd?b.Rd:!1;!1!==r&&!1!==b&&(this.I.interval=r,this.I.Z=b,$dv.registerEventCall(this.impressionId,{hg:this.I.interval,ig:this.I.Z}));this.I.interval=this.I.interval||1E3;this.I.Z=this.I.Z||6;this.I.Bf=this.I.Z;b=this.b.Da();this.ve={wb:12,mc:10,lb:30};this.P={Firefox:{ca:115},Chrome:{ca:89},Safari:{ca:38},Explorer:{ca:55},zf:500,Da:b,lb:30};var q=!1,g=0,m=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.ca=0);this.dataObj.spotXmode=this.dataObj.videoEnable||
this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.la=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[90,100,200,250,268,600,618,850,1050,413,50,31]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800,20]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,
250,300,360,600]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50,100,480,320]},{w:1280,h:[100]},{w:640,h:[480,90,360]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446,90]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180,600]},{w:980,h:[90,
120]},{w:900,h:[240]},{w:275,h:[300]},{w:600,h:[400]},{w:168,h:[28]},{w:216,h:[36]},{w:292,h:[30]},{w:1250,h:[155]},{w:375,h:[150]},{w:1E3,h:[125]},{w:1140,h:[200]}];this.dataObj.spotXmode&&(this.la.push({w:320,h:[240]}),this.la.push({w:400,h:[300]}),this.la.push({w:450,h:[338]}),this.la.push({w:600,h:[800]}),this.la.push({w:640,h:[360]}),this.la.push({w:854,h:[480]}),this.la.push({w:500,h:[375]}));this.Cb=this.cf();this.lc=!1;this.Va=function(a,b){this.window.cd||(this.window.cd=[]);this.window.cd.push({caller:a,
kg:b})};this.startTime=(new Date).getTime();this.ke=4;this.Oc=0;this.wc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,fg:17,interval:32};this.kc=!1;this.Pd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.i.Le();this.window.dv_logObject[this.Cb]=a}this.b.a("ie16e")};this.Rb=function(a){this.b.a("ie17");this.Rb=this.lc?function(a){this.i.Kd(a);this.Pd()}:function(a){this.i.Kd(a)};this.Rb(a)};
this.Jc=function(a,b){this.Jc=this.lc?function(a,b){this.i.Jd(a,b);this.Pd()}:function(a,b){this.i.Jd(a,b)};this.Jc(a,b)};this.Pb=function(){this.b.a("s4");this.c=this.ec.Fe(Math.abs(this.I.Z-this.I.Bf));!this.c&&this.V==this.fa.CrossDomain&&this.b.za(this.window)&&(this.I.Z=0);if(this.c)this.Pf(),this.i.Ff(this.c),setTimeout(f,this.ec.xc?10:50);else if(0<this.I.Z)this.I.Z--,this.Qf(),setTimeout(this.Ge(),this.I.interval);else{try{this.V==this.fa.CrossDomain&&(this.b.vd(this.window,this.la)||this.b.za(this.window))?
(this.c=this.b.Ca(this.window),this.i.Id()):this.V==this.fa.SameDomain&&this.b.vd(this.window,this.la)?(this.c=this.b.Ca(window.parent),this.i.Id(),this.ue()):this.I.Z=-1}catch(a){this.I.Z=-1}setTimeout(f,10)}this.b.a("s4e")};this.ue=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.c=b[d],this.window=a.parent);this.b.a("ff26e")};this.Qf=function(){this.dataObj.btreg&&
this.dataObj.ab?this.i.Uf():this.i.Vf()};this.Pf=function(){this.b.a("s9");this.Xa=!0;this.i.Rf();this.b.a("s9e")};this.le=function(){this.dataObj.Pa=this.X("adsrv",this.ea)||"";this.dataObj.btreg=this.X("btreg",this.ea)||"";this.dataObj.Bd=this.X("plcid",this.ea)||"";"8"==this.dataObj.Pa&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.ab=this.X("btadsrv",this.ea)||"";this.dataObj.Tc=this.X("adid",this.ea)||"";this.dataObj.Cb=this.Cb;this.dataObj.pf=this.X("isbtregex",
this.wa)||"";this.dataObj.yb=this.X("ctx",this.ea)||"";this.dataObj.xb=this.X("cmp",this.ea)||"";this.dataObj.qf=this.X("lomd",this.wa)||"";this.dataObj.findclass=this.X("findclass",this.wa)||"";this.dataObj.displaynon=this.X("displaynon",this.wa)||"";this.dataObj.Yc=this.X("bsdvview",this.wa)||"";var a=this.X("bttag",this.wa)||"";this.dataObj.vb=0<a.length?a.split("|"):[];a=this.X("btattb",this.wa)||"";this.dataObj.Qa=0<a.length?a.split("|"):[];this.dataObj.Ec="1"==this.X("seltag",this.wa)?!0:!1;
if(a=this.X("unit",this.wa)||"")a=a.toLowerCase().split("x"),this.dataObj.Hd=a[0]&&!isNaN(a[0])?parseInt(a[0]):0,this.dataObj.Gd=a[1]&&!isNaN(a[1])?parseInt(a[1]):0};this.Cd=function(a){a=this.Lb(a);return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.Lb=function(a){if(!this.dvObj)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=d&&b.push(d);window&&(d=this.dvObj.pubSub.publish(a[c],window.$frmId)||null,null!=d&&b.push(d))}return b};
this.Ud=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.ea+="&TKH="+this.dataObj.serverSettings.TKH)};this.ze=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};
this.inViewManager=function(){try{Array.prototype.indexOf||this.ze();this.Ud();this.le();this.i=new F(this.me,this.ve,this.dataObj);this.ja=l(this.dataObj,this.i);this.dataObj.isRTNsDisabled&&(this.Lb=function(){return[]});this.lc=this.window.dv_logObject?!0:!1;this.Wf();this.pe=new ba(this.dataObj,this.window,this.c,this.V,this.fa,this.dvObj);this.ec=new aa(this.dataObj,this.la,this.window,this.i,this.V,this.pe);var a=window.parent;"589953"==this.dataObj.yb&&"587351"==this.dataObj.xb||"589953"==
this.dataObj.yb&&"616389"==this.dataObj.xb||"polite"==this.dataObj.qf?(setTimeout(d,15E3),this.b.zb.add("load",function(){setTimeout(d,1E3)},!1,a,!1)):d()}catch(b){var c=this;this.Ka(function(){c.Va("inViewManager",b);c.i.ob("inViewManager",b);c.ja.ga(c.logEvents.errorlevel1)},"inViewManager",b)}};this.sb=function(a){this.b.a("ie20");-6!=a.g&&(-3==a.g||-5!=a.g&&0>a.g&&-1==this.I.Z)&&(this.Lc(),this.sb=function(){})};this.Lc=function(){this.ja.ga(this.logEvents.nonMeasurable);this.Lb(["IABNotMeasuredImpression"]);
this.Lc=function(){}};this.Wa=function(a,b){a.b.a("ie21");if(0<=b.g||-5==b.g&&-1>=a.I.Z){if(a.dvObj&&a.impressionId){a.b.a("ie23");var c=a.Cd(["IABMeasuredImpression"]);a.b.a("ie24");a.ja.ga(a.logEvents.startMeasure,c)}else a.ja.ga(a.logEvents.startMeasure);a.kc=!0;a.Wa=function(){};a.sb=function(){}}a.b.a("ie22")};this.Pc=function(a){this.b.a("ie25");if(this.i.fd()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.Cd(["IABViewableImpression"]),this.b.a("ie29"),this.ja.ga(this.logEvents.iabViewable,
a)):this.ja.ga(this.logEvents.iabViewable),q=!0,this.Pc=function(){};this.b.a("ie26")};this.we=function(a){if(q&&this.i.fd())for(g+=a,a=0;a<m.length;a++)null!=m[a]&&g>=1E3*m[a]&&(this.Lb(["IABAdViewable"+m[a]+"Seconds"]),m[a]=null);else g=0};var w="hidden",h=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){w=vis[a];break}a=1==this.b.cb("fcs");var b=!1;try{this.b.hb(this.window),b=!0}catch(c){}var d=!1;try{this.b.hb(this.window.top),
d=!0}catch(c){}var f=null,f=a&&b&&this.O.U==this.da.IE?function(){var a=k.b.hb(k.window);k.V==k.fa.OnPage&&(a=a&&k.Cc);return a}:a&&d?function(){var a=!0,a=k.b.hb(k.window.top);k.V==k.fa.OnPage&&(a=a&&k.Cc);return a}:"undefined"!==typeof document[w]?function(){return!k.window.document[w]}:d?function(){return k.b.hb(k.window.top)}:function(){return!0};this.hasFocus=function(){try{return f()}catch(a){h++,5<=h&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.uc=function(a){var b=
a.va.Qe();a.b.a("ie12");null==this.c||-3==b.g||a.hasFocus()||(b.g=0);a.b.a("ie13");u=b;a.Ad.update(b.H,a.hasFocus(),b.g,a.ba.interval);a.i.Yf(a.Ad.Ye());return b};var c;this.Xb=function(a){var b;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(b=dvObj.tags[$uid].getTimeDiff())}catch(d){}a.ba.interval=b-c||100;c=b;a.b.a("ie1");b=a.c?a.c.Db||a.window:a.window;a.va.c=a.c;a.va.window=b;a.b.a("ie2");b=a.uc(a);a.Xa&&(-1==b.g||-2==b.g)&&-1<=a.I.Z&&($dv.registerEventCall($uid,{dvp_rlad:$dv.tags[$uid].getTimeDiff()}),
$dv.registerEventCall($uid,{dvp_rlr:Math.abs(b.g)}),a.Fd(a),a.Pb());a.b.a("ie3");-5==b.g&&(a.I.Z--,a.i.Ld(),a.Ua||(a.Ua=function(b){b=a.va.Fb(b);a.i.nb(b)}));a.b.a("ie4");a.Ua&&0<b.g&&(a.Ua(b),a.Ua=null);a.b.a("ie5");if(a.Xa&&!a.Kc){a.Kc=!0;var f=a.va.Fb(b);a.i.nb(f)}-5==b.g&&-1<=a.I.Z&&($dv.registerEventCall($uid,{dvp_rlad:$dv.tags[$uid].getTimeDiff()}),$dv.registerEventCall($uid,{dvp_rlr:Math.abs(b.g)}),a.Fd(a),a.Pb(),b=a.uc(a),-5==b.g&&0<a.I.Z&&a.i.Mf());a.b.a("ie6");a.Jc(b,a.ba.interval);a.b.a("ie7");
a.Rb(b);a.b.a("ie8");a.i.Nd(b.aa);a.sb(b);a.b.a("ie9");a.Wa(a,b);a.b.a("ie10");a.Pc();a.b.a("ie11");a.we(a.ba.interval);a.b.a("ie12");return b};this.Fd=function(a){a.Xa=!1;a.c=null;a.ec.Lf();a.va.ef()};this.Se=function(){this.b.a("s26");var a=this;return function(){try{a.Xb(a)}catch(b){a.Ka(function(){a.Oc<a.ke&&(a.Oc++,a.Va("getIntervalCallback",b),a.i.ob("getIntervalCallback",b),a.ja.ga(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.kd=function(a){var b=this;return function(){b.Ka(function(){b.ja.ga(b.logEvents[a])},
"getReportEventCallback")}};this.Ge=function(){var a=this;return function(){a.Ka(function(){a.Pb();a.c||a.i.Qb()},"getAdLocateCallback")}};this.gb=function(){var a=this;return function(b){try{b||(b=a.window.event),a.Cc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ka(function(){a.Va("getFocBluEventCallback",c);a.i.ob("getFocBluEventCallback",c);a.ja.ga(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.$d=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=
this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.i.Me().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.kc,totalPageTime:(a.i.rc()-a.i.af())/1E3,notApplicableTime:a.i.hd()/1E3}}catch(f){return{}}}}}catch(b){}};this.ae=function(){try{if(this.dvObj&&
this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=u.g;0<=u.g&&u.u&&u.u.f&&(a.adWidth=u.u.f.o,a.adHeight=u.u.f.j);return a};a.VA.getAdElem=function(){return k.c}}}catch(b){}};this.$d();this.start=function(){this.b.a("s35");this.Af(this);var a;this.ba&&this.ba.Ga&&this.ba.Ga[this.mb]&&(a=this.ba.Ga[this.mb].zb);if(a)for(var b=a.length,c=0;c<b;c++)this.Dd[a[c]]=this.kd(a[c]),this.Oa(this.window,
a[c],this.Dd[a[c]]);this.Zf();this.ba&&this.ba.Ga&&this.ba.Ga[this.mb]&&this.ba.Ga[this.mb].Od&&setTimeout(this.If(),this.ba.Ga[this.mb].Od)};this.If=function(){var a=this;return function(){a.kd("timeout")();clearInterval(a.interval);a.ja.ga=function(){}}};this.Af=function(a){try{var b=a.uc(a);-5==b.g&&(this.i.Ld(),this.Ua||(this.Ua=function(b){b=a.va.Fb(b);a.i.nb(b)}));if(a.Xa)if(this.Kc=!0,-5!=b.g){var c=a.va.Fb(b);a.i.nb(c)}else a.i.nb("true");a.i.Nd(b.aa);var d=a.va.Ie(b,a.i.hd());a.i.Tf(d);a.i.Md(b.g);
a.Rb(b);a.sb(b);a.Wa(a,b)}catch(f){a.Ka(function(){a.Va("onStartReport",f);a.i.ob("onStartReport",f);a.ja.ga(a.logEvents.errorlevel1)},"onStartReport",f)}};this.Zf=function(){this.Oa(this.window,"blur",this.gb());this.Oa(this.window,"focus",this.gb());this.Oa(this.window.document,"click",this.gb());this.Oa(this.window.document,"mousedown",this.gb());this.Oa(this.window.document,"mouseup",this.gb())};this.Oa=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:
b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.Wf=function(){this.b.a("ff24");this.V==this.fa.CrossDomain?this.b.za(this.window)||this.b.yc(this.window)||this.b.Gb()||this.b.Hb(this.V,this.O,this.dvObj)||(this.O.U!=this.da.Firefox&&this.O.U!=this.da.IE?this.i.Xf():this.O.U==this.da.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.i.Hc()):window.document.body.getBoundingClientRect||
this.i.Hc();this.wc=this.i.Zc();this.b.a("ff24e")};this.Ka=function(a,b,c){try{a()}catch(d){try{0<this.yd&&(this.yd--,a=c||d,b=b||"unknown caller",this.Va(b,a),this.i.ob(b,a),this.ja.ga(k.logEvents.errorlevel1))}catch(f){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(b){(new dv_CustomClientViewAssureService(b)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs697");
if(tagObject){var serviceParams=tagObject.services.avs697;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(b){};
